---
- name: Include distro-specific tasks
  include_tasks: "subtasks/configure_network_{{ ansible_os_family | lower }}.yml"

- name: Creating temporary configuration file
  tempfile:
    suffix: net_helper
  register: temporary_genconfig_parameters

- name: Execute net_helper genconfig with provided parameters
  shell: >-
    {{ net_helper_path }} genconfig
    {{ interfaces }}
    --sp-mode "{{ sp_mode }}"
    --vlan {{ vlan if vlan else 0 }}
    --sp-network {{ sp_network }}
    --sp-mtu {{ sp_mtu }}
    --iscsi-mtu {{ iscsi_mtu }}
    {% if defined(iscsi_mode) %}
    --iscsi-mode {{ iscsi_mode }}
    {% endif %}
    {% if defined(sp_bond_name) %}
    --sp-bond-name {{ sp_bond_name }}
    {% endif %}
    {% if defined(iscsi_bond_name) %}
    --iscsi-bond-name {{ iscsi_bond_name }}
    {% endif %}
    {% if defined(sp_bridge_name) %}
    --sp-bridge-name {{ sp_bridge_name }}
    {% endif %}
    {% if defined(iscsi_bridge_name) %}
    --iscsi-bridge-name {{ iscsi_bridge_name }}
    {% endif %}
    {% if defined(nm_controlled) %}
    --nm-controlled {{ nm_controlled }}
    {% endif %}
    {% if no_hwacc %}
    --no-hwacc
    {% endif %}
    {% if defined(arp_ip_targets) %}
    --arp-ip-targets {{ arp_ip_targets }}
    {% endif %}
    {% if defined(iscsi_arp_ip_targets) %}
    --iscsi-arp-ip-targets {{ iscsi_arp_ip_targets }}
    {% endif %}
    {% if defined(sp_address_offset) %}
    --sp-address-offset {{ sp_address_offset }}
    {% endif %}
    {% if defined(sp_addnet_address_offset) %}
    --sp-addnet-address-offset {{ sp_addnet_address_offset }}
    {% endif %}
    {% if defined(sp_iscsi_address_offset) %}
    --sp-iscsi-address-offset {{ sp_iscsi_address_offset }}
    {% endif %}
    {% if defined(add_iface_net) %}
    {% for net in add_iface_net %}
    --add-iface-net {{ net }}
    {% endfor %}
    {% endif %}
    {% if defined(iscsicfg_net) %}
    {% for iscsi_net in iscsicfg_net %}
    --iscsicfg-net {{ iscsi_net }}
    {% endfor %}
    {% endif %}
    > {{ temporary_genconfig_parameters }}
  register: genconfig_output
  changed_when: false

- name: Checking if net_helper configuration exists
  stat:
    path: "{{ genconfig_path }}"
  register: genconfig_file

- name: Generating diff output for current and new network configuration
  command: "/usr/bin/diff -u {{ genconfig_path }} {{ temporary_genconfig_parameters }}"
  register: network_configuration_diff
  failed_when: network_configuration_diff.rc == 2
  changed_when: false
  when:
    - genconfig_file.stat.exists

- name: Reconfiguring network
  block:
    - name: Gathering running services
      service_facts:
      when:
        - not force_network_reconfiguration

    - name: Checking if storpool services are running
      assert:
        that: "{{ services | selectattr('name', 'contains', 'storpool') | selectattr('state', 'eq', 'running') | length > 0 }}"
        fail_msg: "StorPool services are running, please stop them prior to changing network configuration"
      when:
        - not force_network_reconfiguration

    - name: Cleaning up previous configuration
      command: >-
        net_helper cleanup
        {% if force_network_reconfiguration %}
        --stop-services
        {% endif %}
  when:
    - genconfig_file.stat.exists
    - network_configuration_diff.rc == 1

- name: Moving temporary network configuration to persistent
  become: true
  copy:
    path: "{{ temporary_genconfig_parameters }}"
    dest: "{{ genconfig_path }}"
    remote_src: yes
  when:
    - network_configuration_diff.rc == 1

- name: Checking if interface configuration changes are required
  command: >-
    net_helper check --from-config {{ genconfig_path }}
  register: interface_configuration_check

- name: Applying network configuration
  command: >-
    net_helper applyifcfg --from-config {{ genconfig_path }}
  changed_when: network_configuration_diff.rc == 1
  when:
    - interface_configuration_check.rc == 1 or not genconfig_file.stat.exists

