---
- name: Configure Network
  include_tasks: "configure_network.yml"
  when:
  - sp_configure_network is defined and
    sp_configure_network | bool

- name: Generate VF configuration
  include_tasks: "vf_generate_config.yml"
  when:
    - sp_vm is defined and
      not sp_vm | bool
